"""
AI Detector
Today's challenge is inspired by the release of ChatGPT on November 30, 2022.
Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:

It contains two or more dashes (-).
It contains two or more sets of parenthesis (()). Text can be within the parenthesis.
It contains three or more words with 7 or more letters.
Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters as part of a word.
If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".

1. detect_ai("The quick brown fox jumped over the lazy dog.") should return "Human".
2. detect_ai("The hypersonic brown fox - jumped (over) the lazy dog.") should return "Human".
3. detect_ai("Yes - you're right! I made a mistake there - let me try again.") should return "AI".
4. detect_ai("The extraordinary students were studying vivaciously.") should return "AI".
"""


def detect_ai(text):
    # dashes
    if text.count("-") >= 2:
        return "AI"
    # parenthesis
    if text.count("(") >= 2 and text.count(")") >= 2:
        return "AI"
    # 7-letter words
    long_words = 0
    for word in text.split(" "):
        clean_word = "".join(c for c in word if c.isalpha())
        if len(clean_word) >= 7:
            long_words += 1
        if long_words >= 3:
            return "AI"
    return "Human"


print(detect_ai("The hypersonic brown fox - jumped (over) the lazy dog."))
